name: tabata_timer
description: "Tabata Timer Flutter Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Suite
      fonts:
        - asset: assets/fonts/SUITE-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITE-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITE-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITE-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITE-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITE-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITE-Heavy.ttf
          weight: 900

icons_launcher:
  image_path: 'assets/icon_image.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#000000'
      adaptive_foreground_image: 'assets/icon_image_foreground.png'

    ios:
      enable: true
      image_path: 'assets/icon_image.png'
      adaptive_background_color: '#000000'